[phases]
setup = "cd catalogo && composer install && cp .env.example .env && php artisan key:generate"
build = "cd catalogo && php artisan migrate"
start = "cd catalogo && php artisan serve --host=0.0.0.0 --port=${PORT}"
